package type;

public enum OperatorType {

    // binary operator
    ADD,
    SUB,
    MUL,
    DIV,
    MOD,
    ASSIGN,
    ADDASSIGN,
    SUBASSIGN,
    MULASSIGN,
    DIVASSIGN,
    MODASSIGN,
    BITWISEANDASSIGN,
    BITWISEORASSIGN,
    BITWISEXORASSIGN,
    LEFTSHIFTINGASSIGN,
    RIGHTSHIFTINGASSIGN,
    GREATERTHAN,
    LESSTHAN,
    GREATERTHANOREQUAL,
    LESSTHANOREQUAL,
    EQUAL,
    NOTEQUAL,
    LOGICALAND,
    LOGICALOR,
    BITWISEAND,
    BITWISEOR,
    BITWISEXOR,
    LEFTSHIFTING,
    RIGHTSHIFTING,

    // unary operator
    CASTING,
    LOGICALNOT,
    NEGATIVESIGN,
    POSITIVESIGN,
    BITWISENEGATE

}
